name: Build

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Wait
        run: sleep 15
      - name: Maven Install
        run: mvn install


